// <auto-generated />
namespace SinglePageApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DONNT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DONNT));
        
        string IMigrationMetadata.Id
        {
            get { return "201803071037441_DONNT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
